### PR TITLE
Update MODLIST.md

### PR DESCRIPTION
**Pull request by Squiddum**
The current modlist is too long, and has some elements I consider 'changes too many things'. I have taken a look at the modlist and picked the ones I see would best fit 8s. If there are any mods you wish to argue for adding, or a dependency mod I missed, please DM me (or write in #developers) explaining why they should be added (although some mods such as MineColonies will never be approved).

### CODE REVIEW

**Review by AppleMangoOrange — CHANGES_REQUESTED** [review]
Small mod I think can stay: Bad Wither No Cookie

Missed dependencies: Collective

Performance Mods that we should definitely keep: Clumps, Entity Culling, Get It Together Drops!, Lazy DFU, Not Enough Crashes (too good of a mod to ever be removed), Better Biome Blend and more

QOL mods that make our lives better by a lot: Controlling, Connected Textures Mod, Better F3, Better Mods Button, Default Options, Ding

These are just some examples that I wanted to point out. This change is too big to make without first being discussed, but I agree that the mod list is too big and that many smaller mods need to be removed like random shulker colours, as those are just unnecessary.

Minecolonies is probably not going for now

**Review by Kasreti — CHANGES_REQUESTED** [review]
i think that clumps, controlling, ding, entityculling, ferritecore, fps reducer, get it goether drops, lazy dfu, not enough crashes, i saw you reorganized the mods at the bottom, but wondering why you want to remove these

**Comment by Squiddum** [comment]
explain what lazyDFU does

**Comment by AppleMangoOrange** [comment]
> explain what lazyDFU does

https://www.youtube.com/watch?v=gXDqJ598kKA
It's there on the mod page

**Pull request closed without merging**
