### PR TITLE
Update MODLIST.md

### PR DESCRIPTION
**Pull request by Squiddum**
hey idk how to edit my old commit, so here's a new one sry. this one has the changes yall suggested, mostly performance and QoL mods
just some things i'd like to ask: what does lazyDFU do, and what's the difference between 'controlling' and 'default options'?

### CODE REVIEW

**Comment by AppleMangoOrange** [comment]
Many major mods have been removed for no apparent reason. Mods like terralith can stay as they are very vanilla-like and following the theme of this pack.

Controlling is a client-side QOL mod that makes it easy to identify contradicting keybinds while default options lets modpack creators set default keys to keybinds without overwriting then on every pack update.

Since a new pull request has been created I will close the last one.

**Comment by Squiddum** [comment]
> Many major mods have been removed for no apparent reason. Mods like terralith can stay as they are very vanilla-like and following the theme of this pack.

like i said, too many mods, so some had to go. but show me a mod you wanna keep with a good explanation and i'll think about it. 

in terralith's case, we dont need a mod to change vanilla overworld worldgen, especially with 1.18's own overhauls

**Comment by AppleMangoOrange** [comment]
> > Many major mods have been removed for no apparent reason. Mods like terralith can stay as they are very vanilla-like and following the theme of this pack.
> 
> like i said, too many mods, so some had to go. but show me a mod you wanna keep with a good explanation and i'll think about it. 
> 
> in terralith's case, we dont need a mod to change vanilla overworld worldgen, especially with 1.18's own overhauls

Having tried out 1.18 with and without terralith i can say that it doesn't affect world gen too much and really blends in well with the vanilla terrain generation. I do not see how we can make such a big change without trying it out in game first.
Also the modpack is not too big, just slightly bulky. So it's not come to the point where we have to sacrifice mods yet

**Review by AppleMangoOrange — CHANGES_REQUESTED** [review]
Try out changes in game and see how they affect the modpack. Add back all performance mods. Extremely small mods like shutup experimental settings can stay, and I will make a new modlist based on the suggested changes.

**Comment by Squiddum** [comment]
> Also the modpack is not too big, just slightly bulky. So it's not come to the point where we have to sacrifice mods yet. The modlist just looks big because of the many small mods

even if you claim most of the mods are small, they add up on loading time, server tps etc. that is why we must critically select the mods and keep the list to its minimum. we do not want a repeat of 3s/7s (inb4 "3s wAy BiGgEr", my point still stands about more mods exerting more stress on server and clients)

**Comment by AppleMangoOrange** [comment]
> > Also the modpack is not too big, just slightly bulky. So it's not come to the point where we have to sacrifice mods yet. The modlist just looks big because of the many small mods
> 
> even if you claim most of the mods are small, they add up on loading time, server tps etc. that is why we must critically select the mods and keep the list to its minimum. we do not want a repeat of 3s/7s (inb4 "3s wAy BiGgEr", my point still stands about more mods exerting more stress on server and clients) 
> 

I feel like this modpack is nowhere near that scale. I don't think we have even reached 100 mods (and I don't intend to, ever).
I also tried this pack out on an old pc I have and it works perfectly fine as it is, so performance is not currently an issue we are facing. It is able to handle running a server and a client at 20 TPS and 45 FPS, which is very good for a more that 10-year-old PC.
Right now the goal is to make the end better and make the modpack immersive as a whole without depending on too many mods.
An example is minecolonies; a relatively light-weight mod that does a lot of the heavy-lifting content-wise, so removing that and mods like it is pretty unwise.
We cannot say that the modpack is laggy or that there are too many mods without first trying it out in-game.
Also, small mods, being small, are only called rarely, and LazyDFU is a great solution to small mods adding to the loading time (look into it for more info).

**Comment by Squiddum** [comment]
do give your changes to the modlist, especially any performance mods. fyi minecolonies is unapproved for other reasons, just ask anyone who was on 3sr (hint: players can claim a ridiculously huge area early game, basically hording entire chunks from other players)

**Comment by AppleMangoOrange** [comment]
> do give your changes to the modlist, especially any performance mods. fyi minecolonies is unapproved for other reasons, just ask anyone who was on 3sr (hint: players can claim a ridiculously huge area early game, basically hording entire chunks from other players) 

About the minecolonies thing, in newer versions it has been made so that you can only claim chunks within one chunk of wherever you have built i.e. you can only claim areas where your colony has been built.

**Comment by Squiddum** [comment]
that's still excluding other players from accessing a portion of the world, an ability that could have disasterous effect if used improperly or with griefing intent. i still see this mod being too risky to add. 

besides, why do we need a colony mod in SMP? rather than every player start their own colony (which i guarantee will happen even if players can share colonies) why not the players make their own town? if more intelligent inhabitants is what you want, i suggest guard villagers as a great addition to vanilla villages (https://www.curseforge.com/minecraft/mc-mods/guard-villagers)

**Comment by AppleMangoOrange** [comment]
> that's still excluding other players from accessing a portion of the world, an ability that could have disasterous effect if used improperly or with griefing intent. i still see this mod being too risky to add. 
> 
> besides, why do we need a colony mod in SMP? rather than every player start their own colony (which i guarantee will happen even if players can share colonies) why not the players make their own town? if more intelligent inhabitants is what you want, i suggest guard villagers as a great addition to vanilla villages (https://www.curseforge.com/minecraft/mc-mods/guard-villagers)

About the griefing, it could easily be done using any other method; methods like TNT are far easier and efficient for that purpose and removing offending colonies if any is very easy.

And like I said, minecolonies is a lightweight and easy way to add content geared towards players who like content that is RPG themed.
So there will be more mods that cater towards other types of players, like exploration-, boss-, tech-, themed etc. which will be pretty similar in function to minecolonies.
If we are to remove minecolonies we would need to add other mods like the Epic Fight mod, but that would impose rpg-themed content on those who don't want it, ruining the experience for others.

**Comment by Kasreti** [comment]
im against minecolonies if its a vanilla+ pack. minecolonies works better in a roleplay settings or packs centered around it imho 
ps: seed suggestion 1248939201, nice island seed :))))))))))

**Comment by AppleMangoOrange** [comment]
I have made a new pull request with few mods removed. Further removal of mods will be done if necessary and wanted. This pull request will be closed after that one is approved.

**Comment by AppleMangoOrange** [comment]
New pull request #17 has been made. Closing this one.

**Pull request closed without merging**
